### ISSUE TITLE
Compiling error using `det()` method

### ISSUE THREAD

**Issue by elsuizo** [termoshtt/ndarray-linalg#138]
I have this error using the `det()` method in a function
```bash
undefined reference to `LAPACKE_dgetrf`
```
in Archlinux

Thanks in advance

**Comment by jturner314** [comment]
It sounds like you need to select a backend. See [this section of the README](https://github.com/termoshtt/ndarray-linalg#blaslapack-backend).

**Comment by elsuizo** [comment]
What confuses me is the part:

"If you creating a library depending on this crate, we encourage you not to link any backend:"

**Comment by jturner314** [comment]
Basically, we recommend that, for maximum flexibility, only the final binary link the backend (not any intermediate libraries). For example, consider this dependency graph for a binary:

```
         binary
        ↙      ↘
  library1    library2
               ↙    │
    ndarray-linalg  │
               ↘    ↓
               ndarray
```

If `library2` links a backend for `ndarray-linalg`, then `binary` cannot do so, so it's nice for `library2` to *not* automatically link any backend and allow `binary` to choose.

The final binary must link a backend in some way so that the necessary LAPACKE routines are included; otherwise, you'll get "undefined reference" errors when building. (Note that this also applies to example/test/bench binaries in library crates, not just binary crates. For example, to run `ndarray-linalg` tests, you have to link a backend with something like `cargo test --features=openblas`.)

Does that help?

**Comment by elsuizo** [comment]
perfect thank you very much for your time !!!
