### ISSUE TITLE
blas in ndarray

### ISSUE THREAD

**Issue by bluss** [termoshtt/ndarray-linalg#15]
ndarray needs the `"blas"` feature to enable using blas for its matrix multiplication (and dot product).

That feature enables calling blas without explicitly picking any particular backend.

Picking backend is tricky in general; indeed none of our libraries should pick one, but enable the end user, final application, to pick the blas/lapack provider.

I was made aware of this crate today, and feel free to report any issues with upstream ndarray. Please note that it's best to migrate to the `Ix1, Ix2` etc dimensionality type aliases, for compatibility with future versions.

**Comment by termoshtt** [comment]
Thank you for your comment, and rust-ndarray!

> 
Please note that it's best to migrate to the Ix1, Ix2 etc dimensionality type aliases, for compatibility with future versions.

I see. I will fix them.

> 
ndarray needs the "blas" feature to enable using blas for its matrix multiplication (and dot product).
That feature enables calling blas without explicitly picking any particular backend.
Picking backend is tricky in general; indeed none of our libraries should pick one, but enable the end user, final application, to pick the blas/lapack provider.

I enable "blas" feature in my last simulation code. Should I enable it on this library?
Since this project already depends on [openblas-src](https://github.com/cmr/openblas-src) via [lapack](https://github.com/stainless-steel/lapack), I do not hesitate to depend on [blas-sys](https://github.com/stainless-steel/blas-sys).

**Comment by bluss** [comment]
If you unconditionally use lapack in your crate, I think you should depend on ndarray's `"blas"` feature.

**Comment by termoshtt** [comment]
Thx, I will reconsider about blas feature when I introduce conditional compilation for LAPACK.

**Comment by termoshtt** [comment]
"blas" feature of ndarray is enabled

**Comment by bluss** [comment]
great
